# Generated by Django 5.2.3 on 2025-07-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='frequency',
            field=models.CharField(blank=True, choices=[('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quinzenal'), ('MONTHLY', 'Mensal')], help_text='Frequência da recorrência (WEEKLY, BIWEEKLY, MONTHLY)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Data final para a criação de agendamentos recorrentes', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='api.appointment'),
        ),
    ]
