# Generated by Django 5.2.3 on 2025-07-19 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_price_service_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='works_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.petshop'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('TUTOR', 'Tutor'), ('PROPRIETARIO', 'Proprietário'), ('GERENTE', 'Gerente'), ('FUNCIONARIO', 'Funcionário')], default='TUTOR', max_length=15),
        ),
    ]
