# Generated by Django 5.2.3 on 2025-07-21 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appointment_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='performers',
            field=models.ManyToManyField(blank=True, related_name='performable_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
