# Generated by Django 5.2.3 on 2025-07-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appointment_employee_service_performers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_schedule',
            field=models.JSONField(blank=True, help_text='\n        Ex: \n        {\n            "monday": {"start": "08:00", "break_start": "12:00", "break_end": "13:00", "end": "17:00"},\n            "tuesday": {"start": "09:00", "break_start": "12:30", "break_end": "13:30", "end": "18:00"}\n        }\n        ', null=True),
        ),
    ]
