# Generated by Django 5.2.3 on 2025-07-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_work_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='buffer_time_minutes',
            field=models.IntegerField(default=0, help_text='Tempo em minutos reservado após o serviço para limpeza/preparação.'),
        ),
    ]
