# Generated by Django 5.2.3 on 2025-07-24 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_service_buffer_time_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.CharField(blank=True, help_text='Motivo do bloqueio (ex: Consulta médica, Feriado)', max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to=settings.AUTH_USER_MODEL)),
                ('pet_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='api.petshop')),
            ],
        ),
    ]
